### ISSUE TITLE
build failure with mysql 5.7

### ISSUE THREAD

**Issue by Joungkyun** [Joungkyun/lib_mysqludf_aes256#6]
when build with mysql 5.7, follow errors occurs:

``` bash
In file included from mysql_aes256.c:40:
In file included from /usr/include/mysql/my_sys.h:26:
/usr/include/mysql/mysql/psi/mysql_thread.h:64:10: fatal error:  'pfs_thread_provider.h' file not found
#include "pfs_thread_provider.h"
         ^
1 error generated.
```
